### ISSUE TITLE
Watchdog is rejected by OpenCPN 5.0 as old and incompatible.

### ISSUE THREAD

**Issue by sbfreddie** [scadaperspective/OpenCPN5#1] opened 2019-05-11 22:11 UTC
Ron:
Thanks, for all you have done for us Mac users.
 I installed Watchdog-Plugin-ov50_2.49.macOS64 with no problems.
When I clicked on the plugins icon OpenCPN rejects the Watchdog plugin saying it is version 1.0 which is apparently not compatible with OpenCPN 5.0.
Perhaps the version number needs to be changed?
I thought I would inform you this way (Through GitHub), I hope it is OK with you?

Thanks,
Freddie

**Comment by scadaperspective** [comment] 2019-05-12 06:27
Hi 

Thanks for the feedback, proves that all I have done is run the code through the compiler :) 

I will check to see if i have missed a pull request or something like that for this plugin  otherwise I will verify it is the same number used for linux and windows.

Apologies for it not working, i test the plugins on my machine however there has been a couple of changes to the base since the release version  most notably the grib plugin so i have been using the latest version instead of a release version which probably doesn’t check the version numbers. Something for me to look into.

 It is good for preventing untested plugins being used, 

the project needs some more help with the cross platform checking so thanks once again.

 I will sort it out as soon as I can spare a few minutes in the office.

**Comment by scadaperspective** [comment] 2019-05-12 08:17
Hi I have checked the version number and for any last minute changes and i have not found any.

I loaded the plugin into a release version of the app with no other plugins apart from the default plugins that come with ov5 and it loaded ok. 

Apart from the icon not being on the toolbar. I have found opening up the preferences/ plugins menu forces a reindex of the plugins the plugin is then available in the menu.

 I have seen the error warning message your speaking of, when it happened i  disabled and reenabled the plugins i had installed and all was ok. Worth trying that. 

I can upload a test version of the base app if you would like. You can have multiple versions of programs installed on a mac. If your using the package manager to install the packages you just need to have the active app as the default name OpenCPN.app

I call the release version something like OpenCPN.release.app and use the testing one with the default name.

I will ask  one of the developing team if they can shed any light beyond trying what i have done. 

I did not completely delete mu install of open cpn and start with a fresh copy and a fresh machine.

Try the above and see what happens. Try a different plugin and see if the same thing happens. 

Let me know and i can put that test base app up for you to try.

**Comment by rgleason** [comment] 2019-05-12 12:51
Ron,
Didier made a PR that added osx and changed  Continuous Integration file .travis  for building OSX
Here is the output on my repos for watchdog  https://travis-ci.org/rgleason/watchdog_pi/jobs/501270365 , perhaps that will help.  Also since Didier [did-g] has been building Watchdog for Mac perhaps what he wrote in .travis.yml   in the OSX section may shed some light on what is needed.
https://github.com/seandepagnier/watchdog_pi/blob/master/.travis.yml

**Comment by scadaperspective** [comment] 2019-05-12 13:17
Thanks Rick will look at this next time i make it into the office.

**Comment by rgleason** [comment] 2019-05-12 13:21
Found the cmake command he used in the travis file, 

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
        cmake -DwxWidgets_CONFIG_EXECUTABLE=/tmp/wx312_opencpn50_macos109/bin/wx-config -DwxWidgets_CONFIG_OPTIONS="--prefix=/tmp/wx312_opencpn50_macos109" -DCMAKE_INSTALL_PREFIX=/tmp/opencpn -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 .. && make -sj2 && make create-pkg;
     fi
- ls -l;

**Comment by rgleason** [comment] 2019-05-12 13:24
Here is the install section that Didier used for OSX
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
      then
        brew install cairo libexif xz libarchive;
        wget http://opencpn.navnux.org/build_deps/wx312_opencpn50_macos109.tar.xz;
        tar xJf wx312_opencpn50_macos109.tar.xz -C /tmp;
        export PATH="/usr/local/opt/gettext/bin:$PATH";
        echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile;
        wget http://opencpn.navnux.org/build_deps/Packages.dmg;
        hdiutil attach Packages.dmg;
        sudo installer -pkg "/Volumes/Packages 1.2.5/Install Packages.pkg" -target "/";
      fi

I don't understand how to trigger .travis to actually build these files, perhaps you can advise?

**Comment by sbfreddie** [comment] 2019-05-12 17:24
Ron:
I tried your suggestions and still no joy with Watchdog.
Here is a "grab" of the plugin window, as you can see there is no Watchdog although Watchdog is install in the .app:
![Plugins installed in OpenCPN](https://user-images.githubusercontent.com/2147774/57585674-1e182900-74a0-11e9-9c27-b680d7ceb5bb.png)

**Comment by sbfreddie** [comment] 2019-05-12 17:56
Ron:
Here is a "grab" shot of the error window which disappears after about 15 seconds:
![Error Window](https://user-images.githubusercontent.com/2147774/57586043-9ed92400-74a4-11e9-9aa1-1ad5b6c1a854.png)

**Comment by scadaperspective** [comment] 2019-05-13 00:13
Thanks Ed  if you have followed the thread here, i have some suggestions from the development team overnight to look at hopefully will be a solution from it 

As soon as i have some time in the office today I will work through it and work out what the differences are. 

Im hopeful for also having a version of LogbookKonni that will compile, 

All the best

**Comment by sbfreddie** [comment] 2019-05-13 00:17
Ron:
Thanks for all your help.
If there is anything I can do please let me know.
I also am an Old EE with over 60 years experience.
Only been doing C and C++ for 20 years though.

Freddie

**Comment by scadaperspective** [comment] 2019-05-13 03:13
Hi Fred,

I have uploaded version2.4 just now (not 2.49)

 If you have the time can you please see if that version is ok with your release version install. 

My hope is that it should be as it is based upon the zip release. 
 I have to do a compare on things to see what the difference really is...  I am presuming the others that you have uploaded are just fine, I saw shipdriver_pi is loaded.

I have had a very long dry spell on hands on coding, compiling. 

A very good friend of mine is in his 90's still working and I am called old !  BTW Sounds like your volunteering :) I am certain that any help would be appreciated. The guys have put together some really good code under the hood, I am still trying to get my head around it all.

I know the team needs help, to take a breath and enjoy the ocean for a while.... 

let me know if that version is running... otherwise into travis I will delve...

/Ron

**Comment by sbfreddie** [comment] 2019-05-13 17:42
Ron:
Tried out your newest version 2.4 but still no joy.
I get the same error and nothing I do can get the plugin to show up in the plugin window.

Thanks,
Fred

**Comment by scadaperspective** [comment] 2019-05-13 21:11
Thanks fred 

Has to be something related to the version numbers I will check that avenue 
I will be in the office by lunch time local today and i will have a clear run at it 

Cheers

**Comment by scadaperspective** [comment] 2019-05-13 22:05
Hi Fred 

See if your application is happy with the version uploaded now...

**Comment by sbfreddie** [comment] 2019-05-13 23:12
Ron:
I downloaded the latest version built at 2:40PM today and still no joy, still get the same message about it being to old.  No amount of messings around will get it to show up.

Thanks,
Ed

**Comment by scadaperspective** [comment] 2019-05-14 00:21
Thanks Ed p

**Comment by scadaperspective** [comment] 2019-05-14 00:39
Thanks Ed 

I have a release version of OpenCPN 5 installed and it doesn’t complain about this plugin installs and runs as expected here so i cannot replicate the problem.  

I have loaded up a binary built from the source tree if you wish to use it until the issue is sorted if you wish to try this plugin is about all I can suggest.

( you can alternately compile from the repository yourself) 


From what i understand there is a check in the api in the release version of a given plugin. 

As far as I am aware  it is a set function in make process that is needed to confirm compatibility.
 
I have checked this information is all there and created a clean build which works here.

The plugin build framework has been updated and changed a few times over the life of the project and there is a huge effort going on at the moment to sort out build automation a couple of packages don’t build without some patches being applied and this might be one that needs the build environment updated. 

Is it just this package from my repository that wont work on your system. If you could confirm that it would be appreciated.

/Ron

**Comment by sbfreddie** [comment] 2019-05-14 00:48
Ron:
All the other packages from your repository work just fine, it is just Watchdog that doesn't work.
I downloaded this version of OpenCPN directly from their WebSite.
There is someone else on the forum that has the exact same problem as I do, so it is not my particular version that is malfunctioning.  Just look at the forum under Mac Plugins and it is the last entry.

Thanks,
Ed

**Comment by scadaperspective** [comment] 2019-05-14 01:12
Hi Ed try the compiled version of the app on my repo and see if it works with it 

You can rename the release to something else.

It has a couple of fixes mostly to do with grib files

**Comment by sbfreddie** [comment] 2019-05-14 01:35
Ron:
I tried your version of OpenCPN but it only works for OS 10.14 (Mojave).
I am on OS 10.13.6.  You will need to adjust your build to include older systems if you want anybody not on Mojave to use it.

Thanks,
Ed

**Comment by scadaperspective** [comment] 2019-05-14 03:18
Thanks Ed,

You have proved a few things. I appreciate the efforts. 

The team is looking at the automation process for deploying release packages and apps so I will close this out as it is related to something upstream.

The most “portable” way to compile for a broad spectrum of users is to compile using Elcapitan with Xcode 8 or 9.4 depending on the project. 

There are not a lot of people offering to compile sadly.

I have on my to do list to try compiling the app under Xcode V9.4 framework. 

If I can get it and watchdog to compile I will load them up for you to try. 

Otherwise if you haven’t done so already try compiling on your machine and if you don’t mind let me know the result. 

All the best 

/Ron

**Closed** 2019-05-14 03:48 UTC
